#
# Copyright (c) 2021 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: Check pull request

on:
  pull_request:
    branches:
    - main
    - v2

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the source
      uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5
      with:
        persist-credentials: false

    - name: Setup Go
      uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c
      with:
        go-version: 1.25.8

    - name: Run the tests
      run: make tests

  verify-model:
    name: Verify model
    permissions:
      contents: read
    runs-on: ubuntu-latest
    env:
      OCM_API_MODEL_REF: main
    steps:
    - name: Checkout the source
      uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5
      with:
        persist-credentials: false

    - name: Setup Go
      uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c
      with:
        go-version: 1.25.8

    - name: Verify ocm-api-model compiles
      run: make verify-model

  verify-sdk:
    name: Verify SDK
    permissions:
      contents: read
    runs-on: ubuntu-latest
    env:
      OCM_SDK_GO_REF: main
    steps:
    - name: Checkout the source
      uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5
      with:
        persist-credentials: false

    - name: Setup Go
      uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c
      with:
        go-version: 1.25.8

    - name: Verify ocm-sdk-go compiles
      run: make verify-sdk
